name: PVP_Maze
main: io.github.rakusan2.pvp_maze_bukkit.PVP_Maze
version: 0.1
commands:
	hello:
		description: Sends hello back
		usage: /<command>
		permission: <plugin name>.hello
		permission-message: I just don't know what went wrong